name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - uses: ponicode/azure-devops-npm-action@master
      with:
          organisation: precise-finance
          project: precise-finance
          registry: precise-npm
          user: danshapir
          password: ${{ secrets.AZURE_PAT }}
          email: dan@precisefinance.ai
          # scope: ponicode
    - run: cp `pwd`/.npmrc ~ # We need the .npmrc file in the $HOME directory
    - name: Setup Node.js
      uses: actions/setup-node@v4.0.0
      with:
        node-version: '18' # Adjust as necessary

    - name: Cache node_modules
      id: cache-node-modules  # Added an ID for this step
      uses: actions/cache@v3
      with:
        path: node_modules  # caching node_modules directly
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-
    
    - name: Install Dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'  # Only run if cache was a miss
      run: npm ci
      
    - name: Run tests
      run: |
        npx prisma generate
        npm run test:ci

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: JEST Tests            # Name of the check run which will be created
        path: reports/jest-*.xml    # Path to test results
        reporter: jest-junit        # Format of test results
    
